# Generated by Django 2.2.2 on 2019-07-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190712_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='massa',
            name='ingredientes_doce',
            field=models.CharField(choices=[('ma', 'maçã'), ('bn', 'banana'), ('nt', 'nutella'), ('ch', 'chocolate'), ('cb', 'chocolate branco'), ('mg', 'morango'), ('dl', 'doce de leite'), ('br', 'brigaderio')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes_integral',
            field=models.CharField(choices=[('mc', 'muçarela'), ('pa', 'parmesão'), ('fg', 'frango'), ('at', 'atum'), ('br', 'brócolis'), ('gz', 'gorgonzola'), ('ov', 'ovo'), ('tm', 'tomate'), ('tc', 'tomate cereja'), ('pl', 'palmito'), ('az', 'azeitona'), ('ap', 'azeitona preta'), ('cb', 'cebola'), ('ml', 'milho')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes_salgada',
            field=models.CharField(choices=[('mc', 'muçarela'), ('pa', 'parmesão'), ('tm', 'tomate'), ('tc', 'tomate cereja'), ('mj', 'manjerião'), ('az', 'azeitona'), ('ap', 'azeitona preta'), ('or', 'oregano'), ('bc', 'bacon'), ('ps', 'presunto'), ('pr', 'peru'), ('fg', 'frango'), ('ov', 'ovo'), ('mc', 'milho'), ('cy', 'catupiry'), ('ch', 'cheddar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes_veg',
            field=models.CharField(choices=[('tf', 'tofu'), ('mc', 'muçarela de castanha'), ('cj', 'carne de jaca'), ('pa', 'parmesão de amendoim'), ('ev', 'ervilha'), ('ap', 'alho-poró'), ('cf', 'couve-flor'), ('rc', 'rúcula'), ('ch', 'champignon'), ('tm', 'tomate'), ('tc', 'tomate cereja'), ('ab', 'abobrinha'), ('mj', 'manjerião'), ('pv', 'presunto vegetal'), ('az', 'azeitona'), ('ap', 'azeitona preta'), ('or', 'oregano')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='massa',
            field=models.CharField(choices=[('np', 'napolitana'), ('ni', 'nova-iorquina'), ('sn', 'siciliana'), ('vt', 'vegetariana'), ('vg', 'vegana'), ('in', 'integral')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='molho',
            field=models.CharField(choices=[('tr', 'tradicional'), ('gz', 'gorgonzola'), ('ps', 'parisiense'), ('pc', 'picante'), ('sj', 'soja')], default='', max_length=60),
        ),
    ]
