# Generated by Django 2.2.3 on 2019-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190714_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('dc', 'doce'), ('veg', 'vegetariano')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='massa',
            name='ingredientes_doce',
        ),
        migrations.RemoveField(
            model_name='massa',
            name='ingredientes_integral',
        ),
        migrations.RemoveField(
            model_name='massa',
            name='ingredientes_salgada',
        ),
        migrations.RemoveField(
            model_name='massa',
            name='ingredientes_veg',
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes',
            field=models.ManyToManyField(to='app.Ingrediente'),
        ),
    ]
