# Generated by Django 2.2.3 on 2019-07-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190715_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('doce', 'doce'), ('vege', 'vegetariano'), ('salg', 'salgado')], max_length=2),
        ),
    ]
