# Generated by Django 2.2.3 on 2019-07-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190715_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massa',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes_doce',
            field=models.CharField(choices=[('ma', 'maçã'), ('bn', 'banana'), ('nt', 'nutella'), ('ch', 'chocolate'), ('cb', 'chocolate branco'), ('mg', 'morango'), ('dl', 'doce de leite'), ('br', 'brigadeiro'), ('pt', 'prestigio'), ('ln', 'leite ninho'), ('so', 'sorvete'), ('ab', 'abacaxi'), ('rj', 'romeu e julieta'), ('om', 'ovomaltine'), ('pc', 'paçoca')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes_integral',
            field=models.CharField(choices=[('mc', 'muçarela'), ('pa', 'parmesão'), ('fg', 'frango'), ('at', 'atum'), ('br', 'brócolis'), ('gz', 'gorgonzola'), ('ov', 'ovo'), ('tm', 'tomate'), ('tc', 'tomate cereja'), ('pl', 'palmito'), ('az', 'azeitona'), ('ap', 'azeitona preta'), ('cb', 'cebola'), ('ml', 'milho')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes_opcoes',
            field=models.CharField(choices=[('mc', 'muçarela'), ('pa', 'parmesão'), ('tm', 'tomate'), ('tc', 'tomate cereja'), ('mj', 'manjerião'), ('az', 'azeitona'), ('ap', 'azeitona preta'), ('or', 'oregano'), ('bc', 'bacon'), ('ps', 'presunto'), ('pr', 'peru'), ('fg', 'frango'), ('ov', 'ovo'), ('mc', 'milho'), ('cy', 'catupiry'), ('ch', 'cheddar')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='massa',
            name='ingredientes_veg',
            field=models.CharField(choices=[('tf', 'tofu'), ('mc', 'muçarela de castanha'), ('cj', 'carne de jaca'), ('pa', 'parmesão de amendoim'), ('ev', 'ervilha'), ('ap', 'alho-poró'), ('cf', 'couve-flor'), ('rc', 'rúcula'), ('ch', 'champignon'), ('tm', 'tomate'), ('tc', 'tomate cereja'), ('ab', 'abobrinha'), ('mj', 'manjerião'), ('pv', 'presunto vegetal'), ('az', 'azeitona'), ('ap', 'azeitona preta'), ('or', 'oregano')], default='', max_length=60),
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
